### ISSUE TITLE
Question - Is it possible to draw dashed lines?

### ISSUE THREAD

**Issue by ghost** [lcdsantos/jquery-drawsvg#13]
Hi! Thanks for the plugin! 

Is it possible to draw dashed lines? I exported a dashed line from Sketch but when I use the plugin to draw the line it removes the dashed.

Cheers!

**Comment by ghost** [comment]
Hello, same here. I would like to know how to animate dashed lines.

**Comment by lcdsantos** [comment]
Currently no.

The plugin uses dashed lines to make the effect, as explained here: [https://jakearchibald.com/2013/animated-line-drawing-svg/](https://jakearchibald.com/2013/animated-line-drawing-svg/)
